trigger:
- none

name: Image and CSS validation in Playwright TS

parameters:
- name: Environment
  displayName: Environment
  type: string
  default: dsnightly
  values:
  - dsci
  - dsnightly
  - dsdemo

- name: pool
  default: 'Azure Pipelines'
  
- name: setBaseLineImage
  displayName: "Do you want to set baseline image?"
  type: string
  values:
    - true
    - false
  
- name: RunByChoice
  displayName: Do you wish to run by tags or exact testcase titles?
  type: string
  values:
    - Tag
    - Title

- name: RunFilterInput
  displayName: Filter input to run testcases
  type: string

variables:
  template_email: './templates/email_template.yml'
  setBaseline: ${{ parameters.setBaseLineImage }}
  env: ${{ parameters.Environment }}

stages:
- stage: playwrightTS
  pool:
    vmImage: 'ubuntu-latest'
  displayName: playwrightTS     
  jobs:   
  - job: TestExecution_${{ parameters.Environment }}
    timeoutInMinutes: 180
    steps:
    - script: |
        curl -O https://downloads.lambdatest.com/hyperexecute/windows/hyperexecute.exe
        chmod +x hyperexecute.exe
        ./hyperexecute.exe -u ramaswamy.shalini -k Ude2C2r1YVeVmheBAOVmyYiAnRAjivG3HZP92A2Ko8ZCWwPBTq -i lamdatest-testexecution.yaml --vars env=${{ parameters.Environment }} --vars setBaseline=${{ parameters.setBaseLineImage }}
      displayName: 'Execute Playwright Tests'
